version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "database"
      POSTGRES_USER: "saizaax"
      POSTGRES_PASSWORD: "password"
    ports:
      - "2345:5432"
    networks:
      - schedule-network
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data
  schedule-backend:
    build: ./
    ports:
      - "8000:8000"
    networks:
      - schedule-network
      - default
    depends_on:
      - postgres
    restart: always
    env_file:
      - .env

networks:
  default:
    external: false
  schedule-network:
    external: true

volumes:
  postgres-data: